{{- if .Values.secret.data -}}
{{- $fullname := include "build_security_pdp.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}
type: Opaque
data:
{{- range $name, $value := .Values.secret.data }}
  {{ $name }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end -}}